#post_index:
#    path:     /
#    defaults: { _controller: "BlogBundle:Post:index" }
#    methods:  GET


#post_show:
#    path:     /post/{id}
#    defaults: { _controller: "BlogBundle:Post:show" }
#    methods:  GET
#    requirements:
#           id: '\d+'
#post_new:
#    path:     /post/new
#    defaults: { _controller: "BlogBundle:Post:new" }
#    methods:  [GET, POST]

#
#post_edit:
#    path:     /post/{id}/edit
#    defaults: { _controller: "BlogBundle:Post:edit" }
#    methods:  [GET, POST]
#    requirements:
#           id: '\d+'
#
#post_delete:
#    path:     /post/{id}/delete
#    defaults: { _controller: "BlogBundle:Post:delete" }
#    methods:  DELETE